contact_links:
  - name: SMF Support Topic
    url: https://www.simplemachines.org/community/index.php?topic=525855.0
    about: This is the main support topic from the official SMF community.
  - name: SMF Tricks Support
    url: https://smftricks.com/index.php?topic=559.0
    about: This is the support topic from the SMF Tricks support boards.